# define GCP credentials file name
variable "credentials" {
  description = "GCP credentials file"
  type        = string
  default     = "credentials.json"
}

# define GCP project name
variable "gcp_project" {
  description = "GCP project name"
  type        = string
}

# define GCP region
variable "region" {
  description = "GCP region"
  type        = string
  default     = "us-central1"
}

# --------------------------------------------------------------

# define VPC name
variable "name" {
  description = "Portion of name to be generated for the VPC network."
  type        = string
  default     = "gcp-demo"
}

# define VPC description
variable "vpc_description" {
  description = "The description of the VPC Network."
  type        = string
  default     = "gcp-demo of VPC"
}

# define VPC routing mode
variable "vpc_routing_mode" {
  description = "Routing mode of the VPC. A 'GLOBAL' routing mode can have adverse impacts on load balancers. Prefer 'REGIONAL'."
  type        = string
  default     = "REGIONAL"
}

variable "auto_create_subnetworks" {
  description = "When set to true, the network is created in 'auto subnet mode' and it will create a subnet for each region automatically across the 10.128.0.0/9 address range. When set to false, the network is created in 'custom subnet mode' so the user can explicitly connect subnetwork resources."
  type        = bool
  default     = false
}

variable "delete_default_internet_gateway_routes" {
  description = "If set, ensure that all routes within the network specified whose names begin with 'default-route' and with a next hop of 'default-internet-gateway' are deleted"
  type        = bool
  default     = false
}

variable "mtu" {
  description = "The network MTU. Must be a value between 1460 and 1500 inclusive. If set to 0 (meaning MTU is unset), the network will default to 1460 automatically."
  type        = number
  default     = 0
}


# --------------------------------------------------------------


# define Public subnet
variable "name_public_subnets" {
  description = "Common portion of names to be generated for the public subnets."
  type        = string
  default     = "public-subnet"
}

variable "public_subnet_description" {
  description = "The description of the public subnet."
  type        = string
  default     = "Generated by Terraform for public use"
}

# define Private subnet
variable "name_private_subnet" {
  description = "Portion of name to be generated for the private subnet."
  type        = string
  default     = "private-subnet"
}

variable "private_subnet_description" {
  description = "The description of the private subnet."
  type        = string
  default     = "Generated by Terraform for private use"
}

# --------------------------------------------------------------

variable "private_ip_google_access" {
  description = "When enabled, VMs in this subnetwork without external IP addresses can access Google APIs and services by using Private Google Access."
  type = bool
  default = true
}

# --------------------------------------------------------------

# define VPC timeout
variable "vpc_timeout" {
  description = "How long a VPC operation is allowed to take before being considered a failure."
  type        = string
  default     = "5m"
}

# define Subnet timeout
variable "subnet_timeout" {
  description = "How long a subnet operation is allowed to take before being considered a failure."
  type        = string
  default     = "10m"
}

# --------------------------------------------------------------

variable "ip_ranges" {
  description = "A map of IP CIDR ranges (including their /x parts) that should be used by the public/private subnets for the various components of the infrastructure. Can use an IP calculator (like https://www.calculator.net/ip-subnet-calculator.html) for help with calculating subnets & IP ranges."
  type = object({
    public          = list(string) # list of CIDR ranges - each with their /x parts (/20 advised) for public subnets of the VPC.
    private_primary = string       # a CIDR range including /x part (/20 advised) for primary IPs in private subnet of the VPC.
  })
}

# --------------------------------------------------------------
